/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.codewithme.bhochhi

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new ConcurrencyModel()

        when:
        def result = app.process

        then:
        result != null
    }
}
